nginx:
  build: images/nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "80:80"
php:
  build: images/php
  volumes:
    - ./app:/var/www/html
  working_dir: /var/www/html
  command: php-fpm
  links:
    - db
    - cache
  ports:
    - "9000:9000"
  environment:
    APP_PATH: /var/www/html/database/migrations
    APP_ENV: local
    APP_DEBUG: 'true'
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_DATABASE: lumen
    DB_USERNAME: lumen
    DB_PASSWORD: secret
    MEMCACHED_HOST: cache
    CACHE_DRIVER: memcached
    JWT_SECRET: 'yolo'
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: lumen
    MYSQL_USER: lumen
    MYSQL_PASSWORD: secret
cache:
  image: memcached

webclient:
  build: web-client
  ports:
    - "3000:3000"